### ISSUE TITLE
add parameter for when limits are cleared

### ISSUE THREAD

**Issue by lochleinn** [jasonedison/coinbase_position_builder_bot#9]
I'd like to be able to set how long the limit orders are on the books before they're cleared. In this instance, I'd like to be able for all the limit orders to accumulate for a week, with the oldest orders deleted on a trailing 7-day timeline.

**Comment by jasonedison** [comment]
Seems simple enough. Now that I have the big math refactor done, I can add this.

**Comment by jasonedison** [comment]
Thinking something like this:

```
// when should we cancel limit orders?
// default behavior is on the next action point (if they didn't fill)
// if CPBB_REBUY_CANCEL is set, this is a number of minutes after the limit order
// creation timestamp that it will be considered ready to cancel if not filled
// 60 minutes * 24 hours * 7 days = 7 days on the books without filling before canceling
CPBB_REBUY_CANCEL: 60*24*7 
```

**Comment by jasonedison** [comment]
new config in release #11 https://github.com/jasonedison/coinbase_position_builder_bot/releases/tag/2.4.0
